#! /usr/bin/env bash

running_sink=$(pactl list sinks | pcregrep -oM "RUNNING\n\tName: (.*)" | grep -oP "(?<=\tName: )(.*)")

if [ -z "$running_sink" ]; then
	echo "alsa_output.pci-0000_00_1b.0.analog-stereo"
else
	echo "$running_sink"
fi
