#! /usr/bin/env bash

declare -i ID;
ID=`xinput list | grep -Eo 'Touchpad\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`;

declare -i STATE;
STATE=`xinput list-props $ID|grep 'Device Enabled'|awk '{print $4}'`;

if [ $STATE -eq 1 ]
then
    xinput set-prop $ID "Device Enabled" 0;
    notify-send -a "Touchpad" "Touchpad disabled";
else
    xinput set-prop $ID "Device Enabled" 1;
    notify-send -a "Touchpad" "Touchpad enabled";
fi
